#include <stacklstt/stacklstt.hpp>
#include <complex/complex.hpp>
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

TEST_CASE_TEMPLATE("stacklstt", T, Complex, int, double) {
  StackLstT<T> a;
  StackLstT<T> pupupu(a);
  CHECK(a.IsEmpty() == true);
  a.Push(T(2));
  CHECK(a.Top() == T(2));
  a.Push(T(1));
  CHECK(a.IsEmpty() == false);
  CHECK(a.Top() == T(1));
  a.Pop();
  CHECK(a.Top() == T(2));
  a.Push(T(3));
  a.Push(T(3));
  a.Push(T(3));
  CHECK(a.Top() == T(3));
  a.Pop();
  CHECK(a.Top() == T(3));
  StackLstT<T> b(a);
  CHECK(b.Top() == a.Top());
  a.Pop();
  b.Pop();
  CHECK(a.Top() == b.Top());
  b.Pop();
  CHECK(b.Top() == T(2));
  b.Pop();
  CHECK_THROWS(b.Top());
  a.Pop();
  a.Pop();
  CHECK_THROWS(a.Top());
  a.Pop();
  CHECK_THROWS(a.Top());
  b.Push(T(7));
  b.Push(T(1));
  StackLstT<T> c(b);
  c.Pop();
  c.Push(T(11));
  CHECK(c.Top() != b.Top());
  CHECK(c.Top() == T(11));
  CHECK(b.Top() == T(1));
  StackLstT<T> s;
  s.Push(T(1));
  s.Push(T(1));
  StackLstT<T> ss;
  ss = s;
  CHECK(ss.Top() == T(1));
  ss.Pop();
  CHECK(ss.Top() == T(1));
  ss.Pop();
  CHECK_THROWS(ss.Top());
  s = ss;
  CHECK_THROWS(s.Top());
  s.Push(T(1));
  ss.Push(T(3));
  s = ss;
  CHECK(s.Top() == T(3));
  s.Push(T(1));
  s.Push(T(1));
  s = ss;
  CHECK(s.Top() == T(3));
  s.Pop();
  CHECK_THROWS(s.Top());
  s.Push(T(1));
  s.Push(T(1));
  s.Push(T(1));
  s.Push(T(1));
  ss = s;
  CHECK(ss.Top() == T(1));
  ss.Pop();
  CHECK(ss.Top() == T(1));
  ss.Pop();
  CHECK(ss.Top() == T(1));
  ss.Pop();
  CHECK(ss.Top() == T(1));
  ss.Pop();
  CHECK_THROWS(ss.Top());
  StackLstT<T> e;
  StackLstT<T> d;
  d.Push(T(5));
  e.Push(T(1));
  e.Push(T(12));
  e.Push(T(3));
  e.Push(T(1));
  d = e; //присваиваю больший
  CHECK(d.Top() == T(1));
  d.Pop();
  CHECK(d.Top() == T(3));
  d.Pop();
  CHECK(d.Top() == T(12));
  d.Pop();
  CHECK(d.Top() == T(1));
  d.Pop();
  CHECK_THROWS(d.Top());
}